export const params = {
  // Shell
  shellType: 'hyperboloid',
  height: 15,
  radiusBottom: 12,
  radiusTop: 8,
  segments: 128,
  twist: 0.0,
  taper: 1.0,
  asymmetryX: 0.0,
  asymmetryZ: 0.0,
  openingAngle: Math.PI * 2,

  // Deformation
  noiseAmplitude: 0.0,
  noiseFrequency: 0.3,
  noiseOctaves: 3,
  noiseSeed: 42,
  attractorStrength: 0.0,
  attractorX: 0,
  attractorY: 10,
  attractorZ: 0,
  waveAmplitude: 0.0,
  waveFrequency: 2.0,
  bendAngle: 0.0,

  // Structure
  ribCount: 0,
  ribThickness: 0.15,
  ribDirection: 'meridional',
  columnCount: 0,
  columnBranching: 3,

  // Skin
  skinType: 'none',
  voronoiCells: 80,
  voronoiRandomness: 0.5,
  voronoiDepth: 0.3,
  islamicStarPoints: 8,
  hexScale: 1.0,
  perforationDensity: 0.5,

  // Fingerprint Pattern
  fpCount: 3,
  fpResolution: 2048,
  fpRidgeSpacing: 14,
  fpDotSize: 3.5,
  fpDotGap: 9,
  fpBackgroundOpacity: 0.3,
  fpSeed: 42,
  fpShowPreview: true,
  // Fingerprint 0
  fp0X: 0.35, fp0Y: 0.40, fp0Scale: 0.55, fp0Rotation: 0.0,
  fp0Type: 'whorl', fp0Tightness: 0.004, fp0Priority: 1,
  // Fingerprint 1
  fp1X: 0.65, fp1Y: 0.45, fp1Scale: 0.50, fp1Rotation: 0.4,
  fp1Type: 'loop', fp1Tightness: 0.003, fp1Priority: 2,
  // Fingerprint 2
  fp2X: 0.50, fp2Y: 0.70, fp2Scale: 0.45, fp2Rotation: -0.3,
  fp2Type: 'arch', fp2Tightness: 0.005, fp2Priority: 3,
  // Fingerprint 3
  fp3X: 0.25, fp3Y: 0.75, fp3Scale: 0.40, fp3Rotation: 0.8,
  fp3Type: 'whorl', fp3Tightness: 0.004, fp3Priority: 4,
  // Fingerprint 4
  fp4X: 0.75, fp4Y: 0.25, fp4Scale: 0.35, fp4Rotation: -0.5,
  fp4Type: 'loop', fp4Tightness: 0.003, fp4Priority: 5,
  // Fingerprint 5
  fp5X: 0.20, fp5Y: 0.30, fp5Scale: 0.30, fp5Rotation: 1.0,
  fp5Type: 'arch', fp5Tightness: 0.005, fp5Priority: 6,
  // Fingerprint 6
  fp6X: 0.80, fp6Y: 0.70, fp6Scale: 0.35, fp6Rotation: 0.2,
  fp6Type: 'whorl', fp6Tightness: 0.004, fp6Priority: 7,
  // Fingerprint 7
  fp7X: 0.50, fp7Y: 0.20, fp7Scale: 0.30, fp7Rotation: -0.7,
  fp7Type: 'loop', fp7Tightness: 0.003, fp7Priority: 8,

  // Scatter
  scatterEnabled: false,
  scatterType: 'sunflower',
  scatterDensity: 50,
  scatterScale: 0.5,
  scatterScaleVariation: 0.3,
  scatterSeed: 42,
  scatterAlignToNormal: true,
  scatterColor: '#f4d03f',

  // Composition
  compositionMode: 'single',
  copyCount: 3,
  copySpacing: 25,
  copyScaleDecay: 0.9,
  copyRotation: 0,
  podiumEnabled: false,
  podiumHeight: 1.5,
  podiumRadius: 16,
  podiumShape: 'circle',

  // Material
  materialColor: '#c8a882',
  metalness: 0.3,
  roughness: 0.5,
  opacity: 1.0,
  wireframe: false,

  // Environment
  envType: 'green',
  envExposure: 1.0,
  fogDensity: 0.003,
  groundColor: '#4a7c3f',
  sunIntensity: 3.0,
  sunAngle: 45,
  sunAzimuth: 225,

  // Postprocessing
  bloomStrength: 0.3,
  bloomRadius: 0.5,
  bloomThreshold: 0.8,

  // Import
  importMode: false,
  importUVMethod: 'smart',
  importScale: 1.0,
  importShowUVCheck: false,
  _importedGeometry: null,
};

export const presets = {
  'Ukrainian Heritage': {
    shellType: 'hyperboloid', height: 20, radiusBottom: 15, radiusTop: 8,
    twist: 0.3, taper: 1.1,
    noiseAmplitude: 0.8, noiseFrequency: 0.3,
    noiseOctaves: 3, noiseSeed: 42, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#f5f5f0', metalness: 0.2, roughness: 0.6,
    skinType: 'vyshyvanka',
    scatterEnabled: true, scatterType: 'sunflower', scatterDensity: 40,
    scatterScale: 0.5, scatterColor: '#f4d03f',
    ribCount: 12, ribDirection: 'meridional',
    compositionMode: 'single', podiumEnabled: true, podiumHeight: 1.5, podiumRadius: 16,
    envType: 'green',
    bloomStrength: 0.3, bloomThreshold: 0.8,
  },
  'Golden Wheat': {
    shellType: 'paraboloid', height: 12, radiusBottom: 20, radiusTop: 14,
    twist: 0, taper: 1.0,
    noiseAmplitude: 0.5, noiseFrequency: 0.2,
    noiseOctaves: 3, noiseSeed: 88, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#d4a017', metalness: 0.6, roughness: 0.3,
    skinType: 'none',
    scatterEnabled: true, scatterType: 'spike', scatterDensity: 200,
    scatterScale: 0.8, scatterColor: '#c8a415',
    ribCount: 0,
    compositionMode: 'single', podiumEnabled: false,
    envType: 'green',
    bloomStrength: 0.5, bloomThreshold: 0.7,
  },
  'Kalyna Garden': {
    shellType: 'torus', height: 14, radiusBottom: 14, radiusTop: 5,
    twist: 0.8, taper: 1.0,
    noiseAmplitude: 1.2, noiseFrequency: 0.35,
    noiseOctaves: 3, noiseSeed: 55, waveAmplitude: 0.5, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#f0ece0', metalness: 0.15, roughness: 0.7,
    skinType: 'none',
    scatterEnabled: true, scatterType: 'kalyna', scatterDensity: 80,
    scatterScale: 0.4, scatterColor: '#cc2222',
    ribCount: 18, ribDirection: 'meridional',
    compositionMode: 'single', podiumEnabled: true, podiumHeight: 1.0, podiumRadius: 16,
    envType: 'green',
    bloomStrength: 0.3, bloomThreshold: 0.8,
  },
  'Clay Imprint': {
    shellType: 'hyperboloid', height: 18, radiusBottom: 14, radiusTop: 7,
    twist: 0.2, taper: 1.1,
    noiseAmplitude: 0.6, noiseFrequency: 0.25,
    noiseOctaves: 3, noiseSeed: 42, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#c4a476', metalness: 0.15, roughness: 0.75,
    skinType: 'fingerprint',
    fpCount: 3, fpResolution: 2048, fpRidgeSpacing: 14,
    fpDotSize: 3.5, fpDotGap: 9, fpBackgroundOpacity: 0.3, fpSeed: 42,
    fp0X: 0.35, fp0Y: 0.40, fp0Scale: 0.55, fp0Rotation: 0.0,
    fp0Type: 'whorl', fp0Tightness: 0.004, fp0Priority: 1,
    fp1X: 0.65, fp1Y: 0.45, fp1Scale: 0.50, fp1Rotation: 0.4,
    fp1Type: 'loop', fp1Tightness: 0.003, fp1Priority: 2,
    fp2X: 0.50, fp2Y: 0.70, fp2Scale: 0.45, fp2Rotation: -0.3,
    fp2Type: 'arch', fp2Tightness: 0.005, fp2Priority: 3,
    scatterEnabled: false,
    ribCount: 0,
    compositionMode: 'single', podiumEnabled: true,
    podiumHeight: 1.5, podiumRadius: 16, podiumShape: 'circle',
    envType: 'desert',
    bloomStrength: 0.2, bloomThreshold: 0.85,
  },
  'Desert Bloom': {
    shellType: 'hyperboloid', height: 18, radiusBottom: 14, radiusTop: 6,
    twist: 0.4, taper: 1.2, noiseAmplitude: 1.5, noiseFrequency: 0.4,
    noiseOctaves: 3, noiseSeed: 42, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#c8a882', metalness: 0.4, roughness: 0.5,
    ribCount: 16, ribDirection: 'meridional',
    skinType: 'perforated', perforationDensity: 0.6,
    scatterEnabled: false,
    compositionMode: 'single', podiumEnabled: false,
    envType: 'desert',
    bloomStrength: 0.4, bloomThreshold: 0.8,
  },
  'Crystalline': {
    shellType: 'blob', height: 20, radiusBottom: 10, radiusTop: 10,
    twist: 0, taper: 1.0, noiseAmplitude: 3.0, noiseFrequency: 0.6,
    noiseOctaves: 2, noiseSeed: 77, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#e0e5ec', metalness: 0.9, roughness: 0.1,
    ribCount: 0, skinType: 'voronoi', voronoiCells: 120,
    scatterEnabled: false,
    compositionMode: 'single', podiumEnabled: false,
    envType: 'studio',
    bloomStrength: 0.8, bloomThreshold: 0.6,
  },
  'Organic Flow': {
    shellType: 'torus', height: 12, radiusBottom: 16, radiusTop: 5,
    twist: 1.2, taper: 0.8, noiseAmplitude: 2.0, noiseFrequency: 0.3,
    noiseOctaves: 4, noiseSeed: 123, waveAmplitude: 1.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#b8976a', metalness: 0.2, roughness: 0.7,
    ribCount: 24, ribDirection: 'meridional',
    skinType: 'hexagonal', hexScale: 1.0,
    scatterEnabled: false,
    compositionMode: 'single', podiumEnabled: false,
    envType: 'evening',
    bloomStrength: 0.3, bloomThreshold: 0.8,
  },
  'Minimal Shell': {
    shellType: 'paraboloid', height: 10, radiusBottom: 18, radiusTop: 12,
    twist: 0, taper: 1.0, noiseAmplitude: 0, noiseFrequency: 0.3,
    noiseOctaves: 3, noiseSeed: 42, waveAmplitude: 0.0, bendAngle: 0.0,
    attractorStrength: 0.0,
    materialColor: '#ffffff', metalness: 0.5, roughness: 0.3,
    ribCount: 0, skinType: 'none',
    scatterEnabled: false,
    compositionMode: 'single', podiumEnabled: false,
    envType: 'studio',
    bloomStrength: 0.2, bloomThreshold: 0.9,
  },
};
